// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1002_GCGetUserData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from 1002_GCGetUserData.proto</summary>
  public static partial class GCGetUserDataReflection {

    #region Descriptor
    /// <summary>File descriptor for 1002_GCGetUserData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCGetUserDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChgxMDAyX0dDR2V0VXNlckRhdGEucHJvdG8aElBCUGxheWVyRGF0YS5wcm90",
            "bxoTUEJBY2NvdW50RGF0YS5wcm90bxoYUEJQbGF5ZXJEZXRhaWxEYXRhLnBy",
            "b3RvIpcBCg1HQ0dldFVzZXJEYXRhEgsKA3VpZBgBIAEoBBIkCgxhY2NvdW50",
            "X2RhdGEYAiABKAsyDi5QQkFjY291bnREYXRhEiIKC3BsYXllcl9kYXRhGAMg",
            "ASgLMg0uUEJQbGF5ZXJEYXRhEi8KEnBsYXllcl9kZXRhaWxfZGF0YRgEIAEo",
            "CzITLlBCUGxheWVyRGV0YWlsRGF0YUJJCh1jb20ud2hhbGVpc2xhbmQuZ2Ft",
            "ZS5wcm90b2NvbEIVR0NHZXRVc2VyRGF0YVByb3RvY29sqgIQQmlnSGVhZC5w",
            "cm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BigHead.protocol.PBPlayerDataReflection.Descriptor, global::BigHead.protocol.PBAccountDataReflection.Descriptor, global::BigHead.protocol.PBPlayerDetailDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.GCGetUserData), global::BigHead.protocol.GCGetUserData.Parser, new[]{ "Uid", "AccountData", "PlayerData", "PlayerDetailData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 获取玩家数据返回
  /// </summary>
  public sealed partial class GCGetUserData : pb::IMessage<GCGetUserData> {
    private static readonly pb::MessageParser<GCGetUserData> _parser = new pb::MessageParser<GCGetUserData>(() => new GCGetUserData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GCGetUserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.GCGetUserDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetUserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetUserData(GCGetUserData other) : this() {
      uid_ = other.uid_;
      AccountData = other.accountData_ != null ? other.AccountData.Clone() : null;
      PlayerData = other.playerData_ != null ? other.PlayerData.Clone() : null;
      PlayerDetailData = other.playerDetailData_ != null ? other.PlayerDetailData.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetUserData Clone() {
      return new GCGetUserData(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private ulong uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "account_data" field.</summary>
    public const int AccountDataFieldNumber = 2;
    private global::BigHead.protocol.PBAccountData accountData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBAccountData AccountData {
      get { return accountData_; }
      set {
        accountData_ = value;
      }
    }

    /// <summary>Field number for the "player_data" field.</summary>
    public const int PlayerDataFieldNumber = 3;
    private global::BigHead.protocol.PBPlayerData playerData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBPlayerData PlayerData {
      get { return playerData_; }
      set {
        playerData_ = value;
      }
    }

    /// <summary>Field number for the "player_detail_data" field.</summary>
    public const int PlayerDetailDataFieldNumber = 4;
    private global::BigHead.protocol.PBPlayerDetailData playerDetailData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBPlayerDetailData PlayerDetailData {
      get { return playerDetailData_; }
      set {
        playerDetailData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GCGetUserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GCGetUserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (!object.Equals(AccountData, other.AccountData)) return false;
      if (!object.Equals(PlayerData, other.PlayerData)) return false;
      if (!object.Equals(PlayerDetailData, other.PlayerDetailData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0UL) hash ^= Uid.GetHashCode();
      if (accountData_ != null) hash ^= AccountData.GetHashCode();
      if (playerData_ != null) hash ^= PlayerData.GetHashCode();
      if (playerDetailData_ != null) hash ^= PlayerDetailData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (accountData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AccountData);
      }
      if (playerData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerData);
      }
      if (playerDetailData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlayerDetailData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uid);
      }
      if (accountData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountData);
      }
      if (playerData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerData);
      }
      if (playerDetailData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerDetailData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GCGetUserData other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0UL) {
        Uid = other.Uid;
      }
      if (other.accountData_ != null) {
        if (accountData_ == null) {
          accountData_ = new global::BigHead.protocol.PBAccountData();
        }
        AccountData.MergeFrom(other.AccountData);
      }
      if (other.playerData_ != null) {
        if (playerData_ == null) {
          playerData_ = new global::BigHead.protocol.PBPlayerData();
        }
        PlayerData.MergeFrom(other.PlayerData);
      }
      if (other.playerDetailData_ != null) {
        if (playerDetailData_ == null) {
          playerDetailData_ = new global::BigHead.protocol.PBPlayerDetailData();
        }
        PlayerDetailData.MergeFrom(other.PlayerDetailData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 18: {
            if (accountData_ == null) {
              accountData_ = new global::BigHead.protocol.PBAccountData();
            }
            input.ReadMessage(accountData_);
            break;
          }
          case 26: {
            if (playerData_ == null) {
              playerData_ = new global::BigHead.protocol.PBPlayerData();
            }
            input.ReadMessage(playerData_);
            break;
          }
          case 34: {
            if (playerDetailData_ == null) {
              playerDetailData_ = new global::BigHead.protocol.PBPlayerDetailData();
            }
            input.ReadMessage(playerDetailData_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
