// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2001_GCGetMapLayerData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from 2001_GCGetMapLayerData.proto</summary>
  public static partial class GCGetMapLayerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for 2001_GCGetMapLayerData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCGetMapLayerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChwyMDAxX0dDR2V0TWFwTGF5ZXJEYXRhLnByb3RvGhRQQk1hcExheWVyRGF0",
            "YS5wcm90byJIChFHQ0dldE1hcExheWVyRGF0YRIOCgZyZXN1bHQYASABKAUS",
            "IwoKbGF5ZXJfZGF0YRgCIAEoCzIPLlBCTWFwTGF5ZXJEYXRhQk0KHWNvbS53",
            "aGFsZWlzbGFuZC5nYW1lLnByb3RvY29sQhlHQ0dldE1hcExheWVyRGF0YVBy",
            "b3RvY29sqgIQQmlnSGVhZC5wcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BigHead.protocol.PBMapLayerDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.GCGetMapLayerData), global::BigHead.protocol.GCGetMapLayerData.Parser, new[]{ "Result", "LayerData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request to Enter the instance
  /// </summary>
  public sealed partial class GCGetMapLayerData : pb::IMessage<GCGetMapLayerData> {
    private static readonly pb::MessageParser<GCGetMapLayerData> _parser = new pb::MessageParser<GCGetMapLayerData>(() => new GCGetMapLayerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GCGetMapLayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.GCGetMapLayerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetMapLayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetMapLayerData(GCGetMapLayerData other) : this() {
      result_ = other.result_;
      LayerData = other.layerData_ != null ? other.LayerData.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCGetMapLayerData Clone() {
      return new GCGetMapLayerData(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    /// <summary>
    ///0success,1failed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "layer_data" field.</summary>
    public const int LayerDataFieldNumber = 2;
    private global::BigHead.protocol.PBMapLayerData layerData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBMapLayerData LayerData {
      get { return layerData_; }
      set {
        layerData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GCGetMapLayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GCGetMapLayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(LayerData, other.LayerData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (layerData_ != null) hash ^= LayerData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (layerData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LayerData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (layerData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LayerData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GCGetMapLayerData other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.layerData_ != null) {
        if (layerData_ == null) {
          layerData_ = new global::BigHead.protocol.PBMapLayerData();
        }
        LayerData.MergeFrom(other.LayerData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 18: {
            if (layerData_ == null) {
              layerData_ = new global::BigHead.protocol.PBMapLayerData();
            }
            input.ReadMessage(layerData_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
