// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2009_GCUpdateMapPlayerData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from 2009_GCUpdateMapPlayerData.proto</summary>
  public static partial class GCUpdateMapPlayerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for 2009_GCUpdateMapPlayerData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCUpdateMapPlayerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiAyMDA5X0dDVXBkYXRlTWFwUGxheWVyRGF0YS5wcm90bxoVUEJNYXBQbGF5",
            "ZXJEYXRhLnByb3RvIlUKFUdDVXBkYXRlTWFwUGxheWVyRGF0YRIRCglwbGF5",
            "ZXJfaWQYASABKAQSKQoPbWFwX3BsYXllcl9kYXRhGAIgASgLMhAuUEJNYXBQ",
            "bGF5ZXJEYXRhQkgKHWNvbS53aGFsZWlzbGFuZC5nYW1lLnByb3RvY29sQhRH",
            "Q01hcFVzZUl0ZW1Qcm90b2NvbKoCEEJpZ0hlYWQucHJvdG9jb2xiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BigHead.protocol.PBMapPlayerDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.GCUpdateMapPlayerData), global::BigHead.protocol.GCUpdateMapPlayerData.Parser, new[]{ "PlayerId", "MapPlayerData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 更新玩家数据
  /// </summary>
  public sealed partial class GCUpdateMapPlayerData : pb::IMessage<GCUpdateMapPlayerData> {
    private static readonly pb::MessageParser<GCUpdateMapPlayerData> _parser = new pb::MessageParser<GCUpdateMapPlayerData>(() => new GCUpdateMapPlayerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GCUpdateMapPlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.GCUpdateMapPlayerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCUpdateMapPlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCUpdateMapPlayerData(GCUpdateMapPlayerData other) : this() {
      playerId_ = other.playerId_;
      MapPlayerData = other.mapPlayerData_ != null ? other.MapPlayerData.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCUpdateMapPlayerData Clone() {
      return new GCUpdateMapPlayerData(this);
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private ulong playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "map_player_data" field.</summary>
    public const int MapPlayerDataFieldNumber = 2;
    private global::BigHead.protocol.PBMapPlayerData mapPlayerData_;
    /// <summary>
    ///new
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBMapPlayerData MapPlayerData {
      get { return mapPlayerData_; }
      set {
        mapPlayerData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GCUpdateMapPlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GCUpdateMapPlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(MapPlayerData, other.MapPlayerData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0UL) hash ^= PlayerId.GetHashCode();
      if (mapPlayerData_ != null) hash ^= MapPlayerData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PlayerId);
      }
      if (mapPlayerData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MapPlayerData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PlayerId);
      }
      if (mapPlayerData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapPlayerData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GCUpdateMapPlayerData other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0UL) {
        PlayerId = other.PlayerId;
      }
      if (other.mapPlayerData_ != null) {
        if (mapPlayerData_ == null) {
          mapPlayerData_ = new global::BigHead.protocol.PBMapPlayerData();
        }
        MapPlayerData.MergeFrom(other.MapPlayerData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (mapPlayerData_ == null) {
              mapPlayerData_ = new global::BigHead.protocol.PBMapPlayerData();
            }
            input.ReadMessage(mapPlayerData_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
