// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2012_CGMapOpenBox.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from 2012_CGMapOpenBox.proto</summary>
  public static partial class CGMapOpenBoxReflection {

    #region Descriptor
    /// <summary>File descriptor for 2012_CGMapOpenBox.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CGMapOpenBoxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChcyMDEyX0NHTWFwT3BlbkJveC5wcm90byJfCgxDR01hcE9wZW5Cb3gSEQoJ",
            "cGxheWVyX2lkGAEgASgEEg4KBmJveF9pZBgCIAEoBRISCgpib3hfc291cmNl",
            "GAMgASgFEhgKEGJveF9zb3VyY2VfcGFyYW0YBCABKAVCSAodY29tLndoYWxl",
            "aXNsYW5kLmdhbWUucHJvdG9jb2xCFENHTWFwT3BlbkJveFByb3RvY29sqgIQ",
            "QmlnSGVhZC5wcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.CGMapOpenBox), global::BigHead.protocol.CGMapOpenBox.Parser, new[]{ "PlayerId", "BoxId", "BoxSource", "BoxSourceParam" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 在地图上使用消耗品
  /// </summary>
  public sealed partial class CGMapOpenBox : pb::IMessage<CGMapOpenBox> {
    private static readonly pb::MessageParser<CGMapOpenBox> _parser = new pb::MessageParser<CGMapOpenBox>(() => new CGMapOpenBox());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGMapOpenBox> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.CGMapOpenBoxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGMapOpenBox() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGMapOpenBox(CGMapOpenBox other) : this() {
      playerId_ = other.playerId_;
      boxId_ = other.boxId_;
      boxSource_ = other.boxSource_;
      boxSourceParam_ = other.boxSourceParam_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGMapOpenBox Clone() {
      return new CGMapOpenBox(this);
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private ulong playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "box_id" field.</summary>
    public const int BoxIdFieldNumber = 2;
    private int boxId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BoxId {
      get { return boxId_; }
      set {
        boxId_ = value;
      }
    }

    /// <summary>Field number for the "box_source" field.</summary>
    public const int BoxSourceFieldNumber = 3;
    private int boxSource_;
    /// <summary>
    ///宝箱来源途径 0无1地图卡2NPC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BoxSource {
      get { return boxSource_; }
      set {
        boxSource_ = value;
      }
    }

    /// <summary>Field number for the "box_source_param" field.</summary>
    public const int BoxSourceParamFieldNumber = 4;
    private int boxSourceParam_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BoxSourceParam {
      get { return boxSourceParam_; }
      set {
        boxSourceParam_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGMapOpenBox);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGMapOpenBox other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (BoxId != other.BoxId) return false;
      if (BoxSource != other.BoxSource) return false;
      if (BoxSourceParam != other.BoxSourceParam) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0UL) hash ^= PlayerId.GetHashCode();
      if (BoxId != 0) hash ^= BoxId.GetHashCode();
      if (BoxSource != 0) hash ^= BoxSource.GetHashCode();
      if (BoxSourceParam != 0) hash ^= BoxSourceParam.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PlayerId);
      }
      if (BoxId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BoxId);
      }
      if (BoxSource != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BoxSource);
      }
      if (BoxSourceParam != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BoxSourceParam);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PlayerId);
      }
      if (BoxId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoxId);
      }
      if (BoxSource != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoxSource);
      }
      if (BoxSourceParam != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoxSourceParam);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGMapOpenBox other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0UL) {
        PlayerId = other.PlayerId;
      }
      if (other.BoxId != 0) {
        BoxId = other.BoxId;
      }
      if (other.BoxSource != 0) {
        BoxSource = other.BoxSource;
      }
      if (other.BoxSourceParam != 0) {
        BoxSourceParam = other.BoxSourceParam;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadUInt64();
            break;
          }
          case 16: {
            BoxId = input.ReadInt32();
            break;
          }
          case 24: {
            BoxSource = input.ReadInt32();
            break;
          }
          case 32: {
            BoxSourceParam = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
