// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 3000_GCEnterBattle.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from 3000_GCEnterBattle.proto</summary>
  public static partial class GCEnterBattleReflection {

    #region Descriptor
    /// <summary>File descriptor for 3000_GCEnterBattle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCEnterBattleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChgzMDAwX0dDRW50ZXJCYXR0bGUucHJvdG8aGFBCQmF0dGxlUGxheWVyRGF0",
            "YS5wcm90byJwCg1HQ0VudGVyQmF0dGxlEhEKCW1vbnN0ZXJJZBgBIAEoBRIm",
            "CglteV9wbGF5ZXIYAiABKAsyEy5QQkJhdHRsZVBsYXllckRhdGESJAoHbW9u",
            "c3RlchgDIAEoCzITLlBCQmF0dGxlUGxheWVyRGF0YUJJCh1jb20ud2hhbGVp",
            "c2xhbmQuZ2FtZS5wcm90b2NvbEIVR0NFbnRlckJhdHRsZVByb3RvY29sqgIQ",
            "QmlnSGVhZC5wcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BigHead.protocol.PBBattlePlayerDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.GCEnterBattle), global::BigHead.protocol.GCEnterBattle.Parser, new[]{ "MonsterId", "MyPlayer", "Monster" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 进入战斗响应
  /// </summary>
  public sealed partial class GCEnterBattle : pb::IMessage<GCEnterBattle> {
    private static readonly pb::MessageParser<GCEnterBattle> _parser = new pb::MessageParser<GCEnterBattle>(() => new GCEnterBattle());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GCEnterBattle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.GCEnterBattleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCEnterBattle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCEnterBattle(GCEnterBattle other) : this() {
      monsterId_ = other.monsterId_;
      MyPlayer = other.myPlayer_ != null ? other.MyPlayer.Clone() : null;
      Monster = other.monster_ != null ? other.Monster.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GCEnterBattle Clone() {
      return new GCEnterBattle(this);
    }

    /// <summary>Field number for the "monsterId" field.</summary>
    public const int MonsterIdFieldNumber = 1;
    private int monsterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MonsterId {
      get { return monsterId_; }
      set {
        monsterId_ = value;
      }
    }

    /// <summary>Field number for the "my_player" field.</summary>
    public const int MyPlayerFieldNumber = 2;
    private global::BigHead.protocol.PBBattlePlayerData myPlayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBBattlePlayerData MyPlayer {
      get { return myPlayer_; }
      set {
        myPlayer_ = value;
      }
    }

    /// <summary>Field number for the "monster" field.</summary>
    public const int MonsterFieldNumber = 3;
    private global::BigHead.protocol.PBBattlePlayerData monster_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBBattlePlayerData Monster {
      get { return monster_; }
      set {
        monster_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GCEnterBattle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GCEnterBattle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonsterId != other.MonsterId) return false;
      if (!object.Equals(MyPlayer, other.MyPlayer)) return false;
      if (!object.Equals(Monster, other.Monster)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MonsterId != 0) hash ^= MonsterId.GetHashCode();
      if (myPlayer_ != null) hash ^= MyPlayer.GetHashCode();
      if (monster_ != null) hash ^= Monster.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MonsterId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonsterId);
      }
      if (myPlayer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MyPlayer);
      }
      if (monster_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Monster);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MonsterId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonsterId);
      }
      if (myPlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyPlayer);
      }
      if (monster_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Monster);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GCEnterBattle other) {
      if (other == null) {
        return;
      }
      if (other.MonsterId != 0) {
        MonsterId = other.MonsterId;
      }
      if (other.myPlayer_ != null) {
        if (myPlayer_ == null) {
          myPlayer_ = new global::BigHead.protocol.PBBattlePlayerData();
        }
        MyPlayer.MergeFrom(other.MyPlayer);
      }
      if (other.monster_ != null) {
        if (monster_ == null) {
          monster_ = new global::BigHead.protocol.PBBattlePlayerData();
        }
        Monster.MergeFrom(other.Monster);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MonsterId = input.ReadInt32();
            break;
          }
          case 18: {
            if (myPlayer_ == null) {
              myPlayer_ = new global::BigHead.protocol.PBBattlePlayerData();
            }
            input.ReadMessage(myPlayer_);
            break;
          }
          case 26: {
            if (monster_ == null) {
              monster_ = new global::BigHead.protocol.PBBattlePlayerData();
            }
            input.ReadMessage(monster_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
