// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBBattlePlayerData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BigHead.protocol {

  /// <summary>Holder for reflection information generated from PBBattlePlayerData.proto</summary>
  public static partial class PBBattlePlayerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for PBBattlePlayerData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PBBattlePlayerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQQkJhdHRsZVBsYXllckRhdGEucHJvdG8aElBCUGxheWVyRGF0YS5wcm90",
            "bxoMUEJEZWNrLnByb3RvIn0KElBCQmF0dGxlUGxheWVyRGF0YRIiCgtwbGF5",
            "ZXJfZGF0YRgBIAEoCzINLlBCUGxheWVyRGF0YRIVCgRkZWNrGAIgASgLMgcu",
            "UEJEZWNrEg4KBmVxdWlwcxgDIAMoBRINCgVidWZmcxgEIAMoBRINCgVpdGVt",
            "cxgFIAMoBUJOCh1jb20ud2hhbGVpc2xhbmQuZ2FtZS5wcm90b2NvbEIaUEJC",
            "YXR0bGVQbGF5ZXJEYXRhUHJvdG9jb2yqAhBCaWdIZWFkLnByb3RvY29sYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BigHead.protocol.PBPlayerDataReflection.Descriptor, global::BigHead.protocol.PBDeckReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BigHead.protocol.PBBattlePlayerData), global::BigHead.protocol.PBBattlePlayerData.Parser, new[]{ "PlayerData", "Deck", "Equips", "Buffs", "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Battle Player's Data
  /// </summary>
  public sealed partial class PBBattlePlayerData : pb::IMessage<PBBattlePlayerData> {
    private static readonly pb::MessageParser<PBBattlePlayerData> _parser = new pb::MessageParser<PBBattlePlayerData>(() => new PBBattlePlayerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PBBattlePlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BigHead.protocol.PBBattlePlayerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PBBattlePlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PBBattlePlayerData(PBBattlePlayerData other) : this() {
      PlayerData = other.playerData_ != null ? other.PlayerData.Clone() : null;
      Deck = other.deck_ != null ? other.Deck.Clone() : null;
      equips_ = other.equips_.Clone();
      buffs_ = other.buffs_.Clone();
      items_ = other.items_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PBBattlePlayerData Clone() {
      return new PBBattlePlayerData(this);
    }

    /// <summary>Field number for the "player_data" field.</summary>
    public const int PlayerDataFieldNumber = 1;
    private global::BigHead.protocol.PBPlayerData playerData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBPlayerData PlayerData {
      get { return playerData_; }
      set {
        playerData_ = value;
      }
    }

    /// <summary>Field number for the "deck" field.</summary>
    public const int DeckFieldNumber = 2;
    private global::BigHead.protocol.PBDeck deck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BigHead.protocol.PBDeck Deck {
      get { return deck_; }
      set {
        deck_ = value;
      }
    }

    /// <summary>Field number for the "equips" field.</summary>
    public const int EquipsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_equips_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> equips_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Equips {
      get { return equips_; }
    }

    /// <summary>Field number for the "buffs" field.</summary>
    public const int BuffsFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_buffs_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> buffs_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Buffs {
      get { return buffs_; }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_items_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> items_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PBBattlePlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PBBattlePlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlayerData, other.PlayerData)) return false;
      if (!object.Equals(Deck, other.Deck)) return false;
      if(!equips_.Equals(other.equips_)) return false;
      if(!buffs_.Equals(other.buffs_)) return false;
      if(!items_.Equals(other.items_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (playerData_ != null) hash ^= PlayerData.GetHashCode();
      if (deck_ != null) hash ^= Deck.GetHashCode();
      hash ^= equips_.GetHashCode();
      hash ^= buffs_.GetHashCode();
      hash ^= items_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerData);
      }
      if (deck_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Deck);
      }
      equips_.WriteTo(output, _repeated_equips_codec);
      buffs_.WriteTo(output, _repeated_buffs_codec);
      items_.WriteTo(output, _repeated_items_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerData);
      }
      if (deck_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Deck);
      }
      size += equips_.CalculateSize(_repeated_equips_codec);
      size += buffs_.CalculateSize(_repeated_buffs_codec);
      size += items_.CalculateSize(_repeated_items_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PBBattlePlayerData other) {
      if (other == null) {
        return;
      }
      if (other.playerData_ != null) {
        if (playerData_ == null) {
          playerData_ = new global::BigHead.protocol.PBPlayerData();
        }
        PlayerData.MergeFrom(other.PlayerData);
      }
      if (other.deck_ != null) {
        if (deck_ == null) {
          deck_ = new global::BigHead.protocol.PBDeck();
        }
        Deck.MergeFrom(other.Deck);
      }
      equips_.Add(other.equips_);
      buffs_.Add(other.buffs_);
      items_.Add(other.items_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (playerData_ == null) {
              playerData_ = new global::BigHead.protocol.PBPlayerData();
            }
            input.ReadMessage(playerData_);
            break;
          }
          case 18: {
            if (deck_ == null) {
              deck_ = new global::BigHead.protocol.PBDeck();
            }
            input.ReadMessage(deck_);
            break;
          }
          case 26:
          case 24: {
            equips_.AddEntriesFrom(input, _repeated_equips_codec);
            break;
          }
          case 34:
          case 32: {
            buffs_.AddEntriesFrom(input, _repeated_buffs_codec);
            break;
          }
          case 42:
          case 40: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
